version: "3.9"
services:
  zuzu_api:
    build: .
    container_name: zuzu_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
